- name: Detect /etc/selinux/config exists
  stat:
    path: /etc/selinux/config
  register: selinux_config

- name: Disable selinux
  selinux:
    policy: targeted
    state: disabled
  when: selinux_config.stat.exists
