- name: Install php extensions
  yum:
    name:
      - "{{php_version}}-php-fpm"
    state: installed

- name: Link php-fpm directories
  file:
    src: "{{item.from}}"
    dest: "{{item.to}}"
    state: link
  with_items:
    - {from: "/var/opt/remi/{{php_version}}/log/php-fpm", to: '/var/log/php-fpm'}
