- name: install tools
  package:
    name: [nano, htop, httpd-tools, libselinux-python, unzip, bind-utils, git, socat, strace]
    state: present
  when: "rhel_version == '7'"

- name: install tools
  package:
    name: [nano, htop, httpd-tools, python3-libselinux, unzip, bind-utils, git, socat, strace]
    state: present
  when: "rhel_version == '8'"
