- include: create_user.yml

- include: install_kctl_tools.yml

- include: install_tools.yml

- include: install_cronie.yml

- include: prepare_home.yml

- include: prepare_ssl.yml

- include: allow_keitaro_user_to_run_kctl_enable_ssl.yml

- include: prepare_config_dirs.yml

- include: generate_selfsigned_certs.yml

- include: generate_dhparam.yml

- include: disable_ipv6.yml

- include: disable_selinux.yml
