- name: Disable swap
  shell: "grep -q '^{{ swap_location }} ' /proc/swaps && swapoff {{ swap_location }} || true"

- name: Remove swap
  file:
    path: "{{ swap_location }}"
    state: absent

- name: Create swap space
  shell: >
    fallocate -l {{ swap_size }}M {{ swap_location }} 2 > /dev/null || \
      dd if=/dev/zero of={{ swap_location }} count={{ swap_size }} bs=1MiB

- name: Make swap file
  command: mkswap {{ swap_location }}

- name: Set swap file permissions
  file: path={{ swap_location }} owner=root group=root mode=0600

- name: Mount swap on boot
  mount: name=none src={{ swap_location }} fstype=swap opts=sw passno=0 dump=0 state=present

- name: Turn swap on
  command: swapon -a

- name: Tweak swap sysctl variables
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_dict: "{{ swap_sysctl_tweaks }}"
