---
- name: Create swap space
  command: fallocate -l {{ swap_size }} {{ swap_location }}
  args:
    creates: "{{ swap_location }}"
  register: swap

- name: Make swap file
  command: mkswap {{ swap_location }}
  when: swap|changed

- name: Set swap file permissions
  file: path={{ swap_location }} owner=root group=root mode=0600
  when: swap|changed

- name: Mount swap on boot
  mount: name=none src={{ swap_location }} fstype=swap opts=sw passno=0 dump=0 state=present
  when: swap|changed

- name: Turn swap on
  command: swapon -a
  when: swap|changed

- name: Tweak swap sysctl variables
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ swap_sysctl_tweaks }}"
