- name: Create directory for stats.json
  file:
    path: "{{ keitaro_stats_json_path | dirname }}"
    state: directory
    owner: "{{ keitaro_user }}"

- name: Schedule generating stats.json job
  cron:
    name: "Generate {{ keitaro_stats_json_path }}"
    job: /usr/local/bin/keitaro-generate_stats_json
    minute: "*/6"
