- name: Download installer
  get_url:
    url: "{{ keitaro_url }}/files/install.php"
    dest: "{{ keitaro_root }}/install.php"
    force: yes

- name: Install Keitaro
  tags: keitaro
  command: |
      {{ php_path }} install.php install \
                                 --ip={{ license_ip }} \
                                 --key={{ license_key }} \
                                 --db-user="{{ db_user }}" \
                                 --db-name="{{ db_name }}" \
                                 --db-password="{{ db_password }}" \
                                 --admin-login="{{ admin_login }}" \
                                 --admin-password="{{ admin_password }}" \
                                 --draft-storage=redis \
                                 --cache-storage=files \
                                 --force-tokudb \
                                 {{ language_option }} \
                                 {{ kversion_option }} \
                                 {{ custom_package_option }}
  vars:
    language_option: "{% if language is defined %}--language={{ language }}{% endif %}"
    kversion_option: "{% if kversion is defined %}--kversion={{ kversion }}{% endif %}"
    custom_package_option: "{% if custom_package is defined %}--custom-package={{ custom_package }}{% endif %}"
  args:
    chdir: "{{ keitaro_root }}"
  become_user: "{{ keitaro_user }}"
  when: "{{ license_key }} != '1111-1111-1111-1111'"
  notify:
    - restart roadrunner

- name: Remove install.php
  file:
    path: "{{ keitaro_root }}/install.php"
    state: absent

- name: Run cron.php to supress warnings in admin panel
  command: "{{ php_path }} cron.php"
  args:
    chdir: "{{ keitaro_root }}"
  become_user: "{{ keitaro_user }}"
