- name: Make systemd nginx extra config dir
  file:
    path: /etc/systemd/system/nginx.service.d
    state: directory

- name: Generate systemd nginx config
  template:
    src: systemd/keitaro-systemd-nginx.conf.j2
    dest: /etc/systemd/system/nginx.service.d/keitaro-systemd-nginx.conf
  notify:
    - restart nginx
