---
- name: Install remi repo.
  yum:
    name: "{{ remi_repo_url }}"
    state: present
  when: "rhel_version == '7'"

- name: Install remi repo.
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
  when: "rhel_version == '8'"

- name: Import remi GPG key.
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: present

- name: List all remi files
  find:
    paths: /etc/yum.repos.d
    patterns: "remi*.repo"
  register: remi_repo

- name: Use keitaro mirror
  replace:
    path: "{{ item.path }}"
    regexp: '^mirrorlist=http.*(/enterprise/.*)$'
    replace: 'mirrorlist={{ remi_repo_base_url }}\1'
  with_items:
    - "{{ remi_repo.files }}"
